[project]
name = "tech-challenge-3"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "selectolax>=0.3.34",
    "sqlalchemy[asyncio]>=2.0.43",
    "uvicorn>=0.35.0",
]
